### ISSUE TITLE
provide direct link to http://datasets.datalad.org

### ISSUE THREAD

**Issue by robertoostenveld** [datalad/datasets.datalad.org#36]
I suggest to add a direct link to http://datasets.datalad.org in the about section, i.e., on the upper right corner of the github page. That directs people that want to browse datasets to the user-friendly web interface. 

<img width="425" alt="Screenshot 2021-12-18 at 12 27 53" src="https://user-images.githubusercontent.com/899043/146639313-f76351ae-268e-4a1f-9c3d-1a23d8fcdc3c.png">

thanks, Robert

**Comment by mih** [comment]
Done! Thx for the suggestion!
