### ISSUE TITLE
Cannot clone `///openneuro`

### ISSUE THREAD

**Issue by tsalo** [datalad/datasets.datalad.org#37]
I'm getting "Couldn't connect to server" when I try to `datalad clone ///openneuro`.

I also can't access http://datasets.datalad.org/.

**Comment by yarikoptic** [comment]
thanks @tsalo for the ping.

there is intermittent issue with our apache2 server... I have improved "dead watch" so it should get restarted more "rapidly" in case of an issue now. 

FWIW according to https://github.com/con/upptime all systems are functioning back normal now ;)
